#Use this file to set the plotting parameters

directories-paths :
  host : 'https://data-argo.ifremer.fr/argo_synthetic-profile_index.txt'
  dac : 'https://data-argo.ifremer.fr/dac'
  repo_directory : 'C:/Users/flapet/OneDrive - NOC/Documents/IDAPro/lib/db_building'

floats_wmo :
  - '1902637'
  - '4903532'
variables_to_plot : 
  - 'TEMP_ADJUSTED'
  - 'PSAL_ADJUSTED'
  - 'CHLA_ADJUSTED'
  - 'BBP700_ADJUSTED'
  - 'DOXY_ADJUSTED'