#Use this file to set the plotting parameters

directories-paths :
  host : 'https://data-argo.ifremer.fr/argo_synthetic-profile_index.txt'
  dac : 'https://data-argo.ifremer.fr/dac'
  repo_directory : 'C:/Users/flapet/OneDrive - NOC/Documents/IDAPro/lib/db_building'

floats_wmo :
  - '1902637'
  - '4903532'
  - 'navis101'
  - 'navis102'
variables_to_plot : 
  - 'TEMP'
  - 'PSAL'
  - 'CHLA'
  - 'CHLA_ADJUSTED'
  - 'BBP700'
  - 'DOXY'

plot_navis : True

products_to_plot :
  - High_res : True

var_to_plot :
 - SST
 - Chla